/**
 * 消息类型常量（页面与 background 之间的通信协议）
 * 所有 chrome.runtime.sendMessage / onMessage 的 type 字段必须使用此处的常量，
 * 禁止散落字符串字面量。
 */
// biome-ignore lint/correctness/noUnusedVariables: 常量对象供各页面与后台脚本引用
export const MessageTypes = Object.freeze({
	DEBUG_LOG: "DEBUG_LOG",
	UPDATE_RULES: "UPDATE_RULES",
	AUTO_SWITCH_TOGGLED: "AUTO_SWITCH_TOGGLED",
	GET_CURRENT_LANG: "GET_CURRENT_LANG",
	RESET_ACCEPT_LANGUAGE: "RESET_ACCEPT_LANGUAGE",
	GET_DOMAIN_RULES: "GET_DOMAIN_RULES",
	UPDATE_CHECK: "UPDATE_CHECK",
	GET_CACHE_STATS: "GET_CACHE_STATS",
	TEST_DOMAIN_CACHE: "TEST_DOMAIN_CACHE",
	CLEAR_DOMAIN_CACHE: "CLEAR_DOMAIN_CACHE",
	RESET_CACHE_STATS: "RESET_CACHE_STATS",
	GET_DYNAMIC_RULES: "GET_DYNAMIC_RULES",
	GET_MATCHED_RULES: "GET_MATCHED_RULES",
	UPDATE_DYNAMIC_RULES: "UPDATE_DYNAMIC_RULES",
	GET_STORAGE_DATA: "GET_STORAGE_DATA",
	GET_MANIFEST_INFO: "GET_MANIFEST_INFO",
});
